language: elixir
sudo: false

elixir: '1.7.3'
otp_release: '21.1'

stages:
  - check formatted
  - test

jobs:
  include:
    - stage: test

    - elixir: '1.5.0'
      otp_release: '19.1'

    - stage: check formatted
      script: mix format --check-formatted
